# RecSys3 - Euclidean Distance Content Based


##### Import Libraries and Dataset 

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, TfidfTransformer
from sklearn.metrics.pairwise import linear_kernel
from scipy.spatial.distance import squareform
from scipy.spatial.distance import pdist

In [2]:
books = pd.read_csv (r'C:\Users\user\OneDrive\Desktop\Artificial Intelligence\clean dataset\books.csv',usecols = ['book_id','authors','original_publication_year','title','average_rating','image_url'])
ratings = pd.read_csv (r'C:\Users\user\OneDrive\Desktop\Artificial Intelligence\clean dataset\ratings.csv')
tags = pd.read_csv (r'C:\Users\user\OneDrive\Desktop\Artificial Intelligence\dataset folder\tags.csv')
bookTags = pd.read_csv (r'C:\Users\user\OneDrive\Desktop\Artificial Intelligence\dataset folder\book_tags.csv')
toRead = pd.read_csv (r'C:\Users\user\OneDrive\Desktop\Artificial Intelligence\dataset folder\to_read.csv')

## Recommend books using the book authors

In [3]:
#Convert a collection of text documents to a matrix of token counts
cv = CountVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')

#generating matrix for authors and it's euclidean distance
author_matrix = cv.fit_transform(books["authors"])
print("Author Matrix:", author_matrix.toarray())

Author Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
#generating euclidean distances based on author matrix 
#using pdist and squareform 
#pdist = computes the Euclidean distance between pairs of objects in m-by-n matrix X , which is treated as m vectors of size n
#squareform = returns a symmetric matrix where Z(i,j) corresponds to the pairwise distance between observations i and j 
author_euclidean_distances = pd.DataFrame(squareform(pdist(author_matrix.toarray())))
print(author_euclidean_distances)

          0         1         2         3         4         5        6     \
0     0.000000  2.828427  2.449490  2.449490  2.449490  2.449490  2.00000   
1     2.828427  0.000000  2.828427  2.828427  2.828427  2.828427  2.44949   
2     2.449490  2.828427  0.000000  2.449490  2.449490  2.449490  2.00000   
3     2.449490  2.828427  2.449490  0.000000  2.449490  2.449490  2.00000   
4     2.449490  2.828427  2.449490  2.449490  0.000000  2.449490  2.00000   
...        ...       ...       ...       ...       ...       ...      ...   
9295  2.449490  2.828427  2.449490  2.449490  2.449490  2.449490  2.00000   
9296  2.449490  2.828427  2.449490  2.449490  2.449490  2.449490  2.00000   
9297  2.449490  2.828427  2.449490  2.449490  2.449490  2.449490  2.00000   
9298  2.449490  2.828427  2.449490  2.449490  2.449490  2.449490  2.00000   
9299  2.449490  2.828427  2.449490  2.449490  2.449490  2.000000  2.00000   

         7         8         9     ...      9290      9291      9292  \
0  

In [5]:
# Build a 1-dimensional array with book titles
titles = books['title']

# series of book's index with the books title 
indices = pd.Series(books.index, index=books['title'])

# Function that get book recommendations based on the euclidean distance score of book authors
def authors_recommendations_euclidean(title):
    idx = indices[title]
    euclidean_dis = list(enumerate(author_euclidean_distances[idx]))
    euclidean_dis = sorted(euclidean_dis, key=lambda x: x[1], reverse=False)
    euclidean_dis = euclidean_dis[1:7]
    book_indices = [i[0] for i in euclidean_dis]
    return titles.iloc[book_indices].to_frame()

In [6]:
authors_recommendations_euclidean("The Hobbit")

title
18    The Fellowship of the Ring (The Lord of the Ri...
152          The Two Towers (The Lord of the Rings, #2)
158   The Return of the King (The Lord of the Rings,...
184   The Lord of the Rings (The Lord of the Rings, ...
941   J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
8834                               Succulent Wild Woman

In [7]:
authors_recommendations_euclidean("The Hobbit")

title
18    The Fellowship of the Ring (The Lord of the Ri...
152          The Two Towers (The Lord of the Rings, #2)
158   The Return of the King (The Lord of the Rings,...
184   The Lord of the Rings (The Lord of the Rings, ...
941   J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
8834                               Succulent Wild Woman

In [8]:
authors_recommendations_euclidean("The Hobbit")

title
18    The Fellowship of the Ring (The Lord of the Ri...
152          The Two Towers (The Lord of the Rings, #2)
158   The Return of the King (The Lord of the Rings,...
184   The Lord of the Rings (The Lord of the Rings, ...
941   J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
8834                               Succulent Wild Woman

In [9]:
authors_recommendations_euclidean("The Hobbit")

title
18    The Fellowship of the Ring (The Lord of the Ri...
152          The Two Towers (The Lord of the Rings, #2)
158   The Return of the King (The Lord of the Rings,...
184   The Lord of the Rings (The Lord of the Rings, ...
941   J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
8834                               Succulent Wild Woman

In [10]:
authors_recommendations_euclidean("The Hobbit")

title
18    The Fellowship of the Ring (The Lord of the Ri...
152          The Two Towers (The Lord of the Rings, #2)
158   The Return of the King (The Lord of the Rings,...
184   The Lord of the Rings (The Lord of the Rings, ...
941   J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
8834                               Succulent Wild Woman

In [11]:
authors_recommendations_euclidean("The Hobbit")

title
18    The Fellowship of the Ring (The Lord of the Ri...
152          The Two Towers (The Lord of the Rings, #2)
158   The Return of the King (The Lord of the Rings,...
184   The Lord of the Rings (The Lord of the Rings, ...
941   J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
8834                               Succulent Wild Woman

In [12]:
authors_recommendations_euclidean("Romeo and Juliet")

title
151                  Macbeth
344                  Othello
701                King Lear
758  The Taming of the Shrew
787              The Tempest
834            Twelfth Night

## Recommend books using the tags provided to the books.

In [13]:
#dataset that joung book tag with tag name and book id 
tags_join_DF = pd.merge(bookTags, tags, left_on='tag_id', right_on='tag_id', how='inner')
tags_join_DF.head()

goodreads_book_id  tag_id   count tag_name
0                  1   30574  167697  to-read
1                  2   30574   24549  to-read
2                  3   30574  496107  to-read
3                  5   30574   11909  to-read
4                  6   30574     298  to-read

In [14]:
#books dataset that include booktag 
booksWithTags = pd.merge(books, tags_join_DF, left_on='book_id', right_on='goodreads_book_id', how='inner')
booksWithTags.head()

book_id          authors  original_publication_year  \
0  2767052  Suzanne Collins                     2008.0   
1  2767052  Suzanne Collins                     2008.0   
2  2767052  Suzanne Collins                     2008.0   
3  2767052  Suzanne Collins                     2008.0   
4  2767052  Suzanne Collins                     2008.0   

                                     title  average_rating  \
0  The Hunger Games (The Hunger Games, #1)            4.34   
1  The Hunger Games (The Hunger Games, #1)            4.34   
2  The Hunger Games (The Hunger Games, #1)            4.34   
3  The Hunger Games (The Hunger Games, #1)            4.34   
4  The Hunger Games (The Hunger Games, #1)            4.34   

                                           image_url  goodreads_book_id  \
0  https://images.gr-assets.com/books/1447303603m...            2767052   
1  https://images.gr-assets.com/books/1447303603m...            2767052   
2  https://images.gr-assets.com/books/1447303603m...            2767052   
3  https://images.gr-assets.com/books/1447303603m...            2767052   
4  https://images.gr-assets.com/books/1447303603m...            2767052   

   tag_id  count           tag_name  
0   30574  11314            to-read  
1   11305  10836            fantasy  
2   11557  50755          favorites  
3    8717  35418  currently-reading  
4   33114  25968        young-adult

In [15]:
#generating matrix for booktag and it's euclidean distance
booktag_matrix = cv.fit_transform(booksWithTags["tag_name"].head(10000))
print("Book Tag Matrix:", booktag_matrix.toarray())

Book Tag Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
booktag_euclidean_distances = pd.DataFrame(squareform(pdist(booktag_matrix.toarray())))
print(booktag_euclidean_distances)

          0         1         2         3         4         5         6     \
0     0.000000  1.414214  1.414214  2.000000  2.000000  1.414214  1.414214   
1     1.414214  0.000000  1.414214  2.000000  2.000000  1.414214  1.414214   
2     1.414214  1.414214  0.000000  2.000000  2.000000  1.414214  1.414214   
3     2.000000  2.000000  2.000000  0.000000  2.449490  2.000000  2.000000   
4     2.000000  2.000000  2.000000  2.449490  0.000000  2.000000  2.000000   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.449490  2.449490  2.449490  2.828427  2.828427  2.449490  2.449490   
9996  2.449490  2.449490  2.449490  2.828427  2.828427  2.449490  2.449490   
9997  1.414214  1.414214  1.414214  2.000000  2.000000  1.414214  1.414214   
9998  2.000000  2.000000  2.000000  2.449490  2.449490  2.000000  2.000000   
9999  1.414214  1.414214  1.414214  2.000000  2.000000  1.414214  1.414214   

          7         8         9     ...      9990      9991    

In [17]:
# Function that get book recommendations based on the eucldiean distance score of book authors
def booktags_recommendations_euclidean(title):
    #the index of title 
    idx = indices[title]
    euclidean_dis = list(enumerate(booktag_euclidean_distances[idx]))
    euclidean_dis = sorted(euclidean_dis, key=lambda x: x[1], reverse=False)
    euclidean_dis = euclidean_dis[1:7]
    book_indices = [i[0] for i in euclidean_dis]
    return titles.iloc[book_indices].to_frame()

In [18]:
booktags_recommendations_euclidean("The Hobbit")

title
16   Catching Fire (The Hunger Games, #2)
31                        Of Mice and Men
107                        Les Misérables
125                            Steve Jobs
149                             Dear John
206                             Atonement

In [19]:
booktags_recommendations_euclidean("Romeo and Juliet")

title
142                                     Deception Point
227                         Love in the Time of Cholera
1128                             The One Minute Manager
1626                                          Galápagos
1741         Edge of Eternity (The Century Trilogy, #3)
1928  A Storm of Swords: Steel and Snow (A Song of I...

## Recommend books using the book title

In [20]:
#generating matrix for title and it's euclidean distance
title_matrix = cv.fit_transform(books["title"])
print("Title Matrix:", title_matrix.toarray())

Title Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [49]:
title_euclidean_distances = pd.DataFrame(squareform(pdist(title_matrix.toarray(),'euclidean')))
print(title_euclidean_distances)

          0         1         2         3         4         5         6     \
0     0.000000  5.477226  4.242641  4.000000  4.000000  4.000000  3.741657   
1     5.477226  0.000000  4.690416  4.472136  4.472136  4.472136  4.242641   
2     4.242641  4.690416  0.000000  2.828427  2.828427  2.828427  2.449490   
3     4.000000  4.472136  2.828427  0.000000  2.449490  2.449490  2.000000   
4     4.000000  4.472136  2.828427  2.449490  0.000000  2.449490  2.000000   
...        ...       ...       ...       ...       ...       ...       ...   
9295  4.242641  4.690416  3.162278  2.828427  2.828427  2.828427  2.449490   
9296  4.690416  5.099020  3.741657  3.464102  3.464102  3.464102  3.162278   
9297  4.000000  4.472136  2.828427  2.449490  2.449490  2.449490  2.000000   
9298  5.477226  5.830952  4.690416  4.472136  4.472136  4.472136  4.242641   
9299  4.000000  4.472136  2.828427  2.449490  2.449490  2.449490  2.000000   

          7         8         9     ...      9290      9291    

In [50]:
# Function that get book recommendations based on the euclidean distance score of book title
def title_recommendations_euclidean(title):
    idx = indices[title]
    euclidean_dis = list(enumerate(title_euclidean_distances[idx]))
    euclidean_dis = sorted(euclidean_dis, key=lambda x: x[1], reverse=False)
    euclidean_dis = euclidean_dis[1:7]
    book_indices = [i[0] for i in euclidean_dis]
    titles.iloc[book_indices].to_frame().head(10)
    return titles.iloc[book_indices].to_frame()

In [51]:
title_recommendations_euclidean("The Hobbit")

title
110   Me Before You (Me Before You, #1)
172                                  It
195            And Then There Were None
1020                        Why Not Me?
1203                   What Is the What
1414             Everything, Everything

In [52]:
title_recommendations_euclidean("Romeo and Juliet")

title
6097                             Juliet
7190     Shakespeare's Romeo and Juliet
110   Me Before You (Me Before You, #1)
172                                  It
195            And Then There Were None
1020                        Why Not Me?

## Recommend books using the publication year

In [53]:
#need to convert the year in books to string 
books['original_publication_year'] = books['original_publication_year'].astype(str)

In [54]:
#generating matrix for title and it's euclidean distance
year_matrix = cv.fit_transform(books["original_publication_year"])
print("Year Matrix:", year_matrix.toarray())

Year Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [55]:
year_euclidean_distances = pd.DataFrame(squareform(pdist(year_matrix.toarray(),'euclidean')))
print(year_euclidean_distances)

          0         1         2         3         4         5         6     \
0     0.000000  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214   
1     1.414214  0.000000  1.414214  1.414214  1.414214  1.414214  1.414214   
2     1.414214  1.414214  0.000000  1.414214  1.414214  1.414214  1.414214   
3     1.414214  1.414214  1.414214  0.000000  1.414214  1.414214  1.414214   
4     1.414214  1.414214  1.414214  1.414214  0.000000  1.414214  1.414214   
...        ...       ...       ...       ...       ...       ...       ...   
9295  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214   
9296  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214   
9297  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214   
9298  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214   
9299  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214  1.414214   

          7         8         9     ...      9290      9291    

In [56]:
# Function that get book recommendations based on the euclidean distance score of book published year
def year_recommendations_euclidean(title):
    idx = indices[title]
    euclidean_dis = list(enumerate(year_euclidean_distances[idx]))
    euclidean_dis = sorted(euclidean_dis, key=lambda x: x[1], reverse=False)
    euclidean_dis = euclidean_dis[1:7]
    book_indices = [i[0] for i in euclidean_dis]
    return titles.iloc[book_indices].to_frame()

In [57]:
year_recommendations_euclidean("The Hobbit")

title
31                                      Of Mice and Men
457                        Their Eyes Were Watching God
667   Think and Grow Rich: The Landmark Bestseller -...
1448     On the Banks of Plum Creek  (Little House, #4)
1687            Death on the Nile (Hercule Poirot, #17)
3776                           The Cost of Discipleship

In [58]:
year_recommendations_euclidean("Romeo and Juliet")

title
242                           A Midsummer Night's Dream
8306                                         Richard II
0               The Hunger Games (The Hunger Games, #1)
1     Harry Potter and the Sorcerer's Stone (Harry P...
2                               Twilight (Twilight, #1)
3                                 To Kill a Mockingbird

In [59]:
year_recommendations_euclidean("Twilight (Twilight, #1)")

title
15   The Girl with the Dragon Tattoo (Millennium, #1)
26  Harry Potter and the Half-Blood Prince (Harry ...
40  The Lightning Thief (Percy Jackson and the Oly...
46                                     The Book Thief
73                                 Looking for Alaska
80                                   The Glass Castle

## Recommendation of books using the authors and tags attributes 




In [60]:
temp_df = booksWithTags.groupby('book_id')['tag_name'].apply(' '.join).reset_index()
temp_df.head()

book_id                                           tag_name
0        1  to-read fantasy favorites currently-reading yo...
1        2  to-read fantasy favorites currently-reading yo...
2        3  to-read fantasy favorites currently-reading yo...
3        5  to-read fantasy favorites currently-reading yo...
4        6  to-read fantasy young-adult fiction harry-pott...

In [61]:
books = pd.merge(books, temp_df, left_on='book_id', right_on='book_id', how='inner')

In [62]:
#corpus = collection of text
#corpus in this case belongs to text with mixture of authors and a
books['corpus'] = (pd.Series(booksWithTags[['authors', 'tag_name']]
                .fillna('')
                .values.tolist()
                ).str.join(' '))

In [63]:
#generating matrix for publication year and it's euclidean distance
corpus_matrix = cv.fit_transform(books["corpus"])
print("Corpus Matrix:", title_matrix.toarray())

Corpus Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [64]:
corpus_euclidean_distances = pd.DataFrame(squareform(pdist(corpus_matrix.toarray())))

In [65]:
print(corpus_euclidean_distances)

          0         1         2         3         4         5         6     \
0     0.000000  2.000000  2.000000  2.449490  2.449490  2.000000  2.000000   
1     2.000000  0.000000  2.000000  2.449490  2.449490  2.000000  2.000000   
2     2.000000  2.000000  0.000000  2.449490  2.449490  2.000000  2.000000   
3     2.449490  2.449490  2.449490  0.000000  2.828427  2.449490  2.449490   
4     2.449490  2.449490  2.449490  2.828427  0.000000  2.449490  2.449490   
...        ...       ...       ...       ...       ...       ...       ...   
9295  3.741657  3.741657  3.741657  4.000000  4.000000  3.741657  3.741657   
9296  3.464102  3.464102  3.464102  3.741657  3.741657  3.464102  3.464102   
9297  3.741657  3.741657  3.741657  4.000000  4.000000  3.741657  3.741657   
9298  3.464102  3.464102  3.464102  3.741657  3.741657  3.464102  3.464102   
9299  5.099020  5.099020  5.099020  5.291503  5.291503  5.099020  5.099020   

          7         8         9     ...      9290      9291    

In [66]:
# Build a 1-dimensional array with book titles
titles = books['title']
indices = pd.Series(books.index, index=books['title'])

# Function that get book recommendations based on the euclidean distance score of book's corpus info
def corpus_recommendations(title):
    idx = indices[title]
    euclidean_dis = list(enumerate(corpus_euclidean_distances[idx]))
    euclidean_dis = sorted(euclidean_dis, key=lambda x: x[1], reverse=False)
    euclidean_dis = euclidean_dis[1:7]
    book_indices = [i[0] for i in euclidean_dis]
    return titles.iloc[book_indices].to_frame()


In [67]:
corpus_recommendations("The Hunger Games (The Hunger Games, #1)")

title
11                            Divergent (Divergent, #1)
26    Harry Potter and the Half-Blood Prince (Harry ...
1600                                               Rant
1624           Prince of Thorns (The Broken Empire, #1)
1900                      Fool's Errand (Tawny Man, #1)
1912  I'm a Stranger Here Myself: Notes on Returning...

In [68]:
corpus_recommendations("The Hobbit")

title
16                 Catching Fire (The Hunger Games, #2)
31                                      Of Mice and Men
1605  Cross My Heart and Hope to Spy (Gallagher Girl...
1614                                  Fantastic Mr. Fox
1673                    Dragon Rider (Dragon Rider, #1)
1906                                         Possession

### All In One (author, title,  year,  tag)


In [69]:
#need to convert the year in books to string 
booksWithTags['original_publication_year'] = booksWithTags['original_publication_year'].astype(str)

In [70]:
#title_tag = collection of text
#corpus in this case belongs to text with mixture of authors and a
books['all'] = (pd.Series(booksWithTags[['authors','title', 'tag_name','original_publication_year']]
                .fillna('')
                .values.tolist()
                ).str.join(' '))

In [71]:
#generating matrix for publication year and it's euclidean distance
all_matrix = cv.fit_transform(books["all"])
print("All In One Matrix:", all_matrix.toarray())

All In One Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [72]:
all_euclidean_distances = pd.DataFrame(squareform(pdist(all_matrix.toarray())))
print(all_euclidean_distances)

          0         1         2         3         4         5         6     \
0     0.000000  2.449490  2.449490  2.828427  2.828427  2.449490  2.449490   
1     2.449490  0.000000  2.449490  2.828427  2.828427  2.449490  2.449490   
2     2.449490  2.449490  0.000000  2.828427  2.828427  2.449490  2.449490   
3     2.828427  2.828427  2.828427  0.000000  3.162278  2.828427  2.828427   
4     2.828427  2.828427  2.828427  3.162278  0.000000  2.828427  2.828427   
...        ...       ...       ...       ...       ...       ...       ...   
9295  6.000000  6.000000  6.000000  6.164414  6.164414  6.000000  6.000000   
9296  5.830952  5.830952  5.830952  6.000000  6.000000  5.830952  5.830952   
9297  6.000000  6.000000  6.000000  6.164414  6.164414  6.000000  6.000000   
9298  5.830952  5.830952  5.830952  6.000000  6.000000  5.830952  5.830952   
9299  6.928203  6.928203  6.928203  7.071068  7.071068  6.928203  6.928203   

          7         8         9     ...      9290      9291    

In [73]:
# Build a 1-dimensional array with book titles
titles = books['title']
indices = pd.Series(books.index, index=books['title'])

# Function that get book recommendations based on the euclidean distance score of book's all in one information 
def all_recommendations(title):
    idx = indices[title]
    euclidean_dis = list(enumerate(all_euclidean_distances[idx]))
    euclidean_dis = sorted(euclidean_dis, key=lambda x: x[1], reverse=False)
    euclidean_dis = euclidean_dis[1:7]
    book_indices = [i[0] for i in euclidean_dis]
    return titles.iloc[book_indices].to_frame()


In [74]:
all_recommendations("The Hobbit")

title
16               Catching Fire (The Hunger Games, #2)
31                                    Of Mice and Men
18  The Fellowship of the Ring (The Lord of the Ri...
21                                   The Lovely Bones
34                                      The Alchemist
52                 Eragon (The Inheritance Cycle, #1)

In [75]:
all_recommendations("Twilight (Twilight, #1)")

title
33            Fifty Shades of Grey (Fifty Shades, #1)
14                          The Diary of a Young Girl
18  The Fellowship of the Ring (The Lord of the Ri...
34                                      The Alchemist
42                                          Jane Eyre
0             The Hunger Games (The Hunger Games, #1)

In [77]:
all_recommendations("The Hunger Games (The Hunger Games, #1)")

title
11                          Divergent (Divergent, #1)
26  Harry Potter and the Half-Blood Prince (Harry ...
18  The Fellowship of the Ring (The Lord of the Ri...
34                                      The Alchemist
47                                     Fahrenheit 451
55                       Breaking Dawn (Twilight, #4)

## Euclidean Distance Content Based Rec System Program